name: Unicafe Tests
on:
  push:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

        #install dependencies and run tests
    - name: Install app dependencies
      run: |
        cd unicafe
        npm install
      env:
        CI: true

      #wait for app to be ready
    - name: Wait for app
      run: npx wait-on http://localhost:5173

      #install dependencies for tests
    - name: Install test dependencies
      run: |
        cd unicafe-tests
        npm install
        npx playwright install chromium

      #run playwright tests
    - name: Run Playwright tests
      run: |
        cd unicafe-tests
        npx playwright test
